# Usa a imagem oficial do MySQL (versão 8.0)
FROM mysql:8.0

# Define variáveis de ambiente padrão (substitua conforme necessário)
ENV MYSQL_ROOT_PASSWORD=root \
    MYSQL_DATABASE=AULADB \
    MYSQL_USER=admin \
    MYSQL_PASSWORD=admin123

# Exponha a porta padrão do MySQL
EXPOSE 3306
